name: 'Buildifier Format Check'
description: 'Checks if Bazel files are properly formatted using buildifier'

inputs:
  buildifier-version:
    description: 'Version of buildifier to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install buildifier
      shell: bash
      run: |
        if [ "${{ inputs.buildifier-version }}" = "latest" ]; then
          BUILDIFIER_VERSION=$(curl -s https://api.github.com/repos/bazelbuild/buildtools/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        else
          BUILDIFIER_VERSION="${{ inputs.buildifier-version }}"
        fi

        echo "Installing buildifier version ${BUILDIFIER_VERSION}"

        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)

        # Map architecture names
        if [ "$ARCH" = "x86_64" ]; then
          ARCH="amd64"
        elif [ "$ARCH" = "aarch64" ]; then
          ARCH="arm64"
        fi

        # Download buildifier
        DOWNLOAD_URL="https://github.com/bazelbuild/buildtools/releases/download/v${BUILDIFIER_VERSION}/buildifier-${OS}-${ARCH}"
        curl -L -o /tmp/buildifier "${DOWNLOAD_URL}"
        chmod +x /tmp/buildifier
        sudo mv /tmp/buildifier /usr/local/bin/buildifier

        buildifier --version

    - name: Get changed files
      shell: bash
      run: |
        echo "Detecting changed Bazel files..."

        # Determine the base ref to compare against
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BASE_REF="${{ github.event.pull_request.base.sha }}"
          HEAD_REF="${{ github.event.pull_request.head.sha }}"
        else
          # For push events, compare with the previous commit
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            # New branch, compare with HEAD~1
            BASE_REF="HEAD~1"
          else
            BASE_REF="${{ github.event.before }}"
          fi
          HEAD_REF="${{ github.sha }}"
        fi

        echo "Comparing $BASE_REF...$HEAD_REF"

        # Get list of changed files that are Bazel files
        git diff --name-only --diff-filter=ACMRT "$BASE_REF" "$HEAD_REF" | \
          grep -E '(^|/)((BUILD|WORKSPACE|MODULE)(\.bazel)?|.*\.bzl)$' > /tmp/bazel_files.txt || true

        if [ -s /tmp/bazel_files.txt ]; then
          echo "Found $(wc -l < /tmp/bazel_files.txt) changed Bazel files:"
          cat /tmp/bazel_files.txt
        else
          echo "No Bazel files changed in this commit"
        fi

    - name: Check formatting with buildifier
      shell: bash
      run: |
        if [ ! -s /tmp/bazel_files.txt ]; then
          echo "✅ No Bazel files to check"
          exit 0
        fi

        echo "Checking Bazel file formatting..."
        EXIT_CODE=0

        while IFS= read -r file; do
          if [ -f "$file" ]; then
            if ! buildifier --mode=check --lint=warn "$file"; then
              echo "❌ File needs formatting: $file"
              EXIT_CODE=1
            fi
          fi
        done < /tmp/bazel_files.txt

        if [ $EXIT_CODE -eq 0 ]; then
          echo "✅ All changed Bazel files are properly formatted"
        else
          echo ""
          echo "❌ Some files are not properly formatted"
          echo "To fix formatting issues, run: buildifier --mode=fix <file>"
          exit 1
        fi
